### ISSUE TITLE
pfring_zc and ntopng packet loss 

### ISSUE THREAD

**Issue by papage** [ntop/PF_RING#146]
Hi all,

I have a few problems getting ntopng to work without significant packet loss. 
My setup is:
Centos7 VM 4core/6GB RAM with a passed-through intel 10G 520 adapter.

PFcount seems ok:
/usr/local/bin/pfcount -i zc:ens160

Absolute Stats: [1'494'382 pkts total][0 pkts dropped][0.0% dropped]
[1'494'382 pkts rcvd][1'140'440'217 bytes rcvd][498'086.65 pkt/sec][3'040.92 Mbit/sec]

Actual Stats: [382'705 pkts rcvd][1'000.06 ms][382'680.89 pps][2.33 Gbps]

NTOPNG shows extreme packet loss. 
Dropped Packets 46,507,909 Pkts [ 90.25 % ] 
Actually is proccesses 60-70K pps when I have 400Kpps

Top shows:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND  
 2771 nobody    20   0 2565496 1.422g   5976 S 204.3 18.6  10:09.36 ntopng  
 1357 redis     20   0  146788   9960   1516 S  30.9  0.1   1:16.68 redis-server    

Is that normal? How can I imporve its perfomance?
I have tried to change RSS=4 and launch ntopng with zc:ens160@0-3 but it did not improve.

Thanx,
sp

Setup details: 
# ethtool -g ens160

Ring parameters for ens160
Pre-set maximums:
RX:             32768
RX Mini:        0
RX Jumbo:       0
TX:             32768
Current hardware settings:
RX:             32768
RX Mini:        0
RX Jumbo:       0
TX:             32768
# cat /proc/net/pf_ring/dev/ens160/info

Name:         ens160
Index:        4
Address:      90:E2:BA:5C:BB:9D
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel ixgbe 82599
TX Queues:    1
RX Queues:    1
Num RX Slots: 32768
Num TX Slots: 32768
# cat /proc/interrupts | grep ens160

 63:         25      34405          0          0          0          0   PCI-MSI-edge      ens160-TxRx-0
 64:          3          0          0          0          0          0   PCI-MSI-edge      ens160
# cat /etc/pf_ring/zc/ixgbe/ixgbe.conf

RSS=1
# cat /etc/pf_ring/zc/ixgbe/ixgbe.start
# 
# cat /etc/ntopng/ntopng.conf

-G=/var/run/ntopng.pid
--interface=zc:ens160
--local-networks="yyy.xxx.0.0/16"
--data-dir=/var/ntopng
--dns-mode=1
--disable-autologout
-x 512000
-g -1

**Comment by cardigliano** [comment]
@simonemainardi any update on this?

**Comment by simonemainardi** [comment]
latest dev build should solve the issue

**Comment by papage** [comment]
Hi all,

I did try the latest updates fro the repo (is that the dev build?) and the issue is not resolved .
The loss is still at "62,526,269 Pkts [ 73.48 % ] " as stated by ntopng. 

Is it possible that more cores are needed for the job? (i am on a 4-core VM with 8G RAM).

Sp

cento.x86_64                            1.3.161220-163                 @ntop    
e1000e-zc.noarch                        3.2.7.1.1065-dkms              @ntop-noarch
i40e-zc.noarch                          1.5.18.1068-1dkms              @ntop-noarch
igb-zc.noarch                           5.3.3.5.1065-dkms              @ntop-noarch
ixgbe-zc.noarch                         4.1.5.1068-dkms                @ntop-noarch
n2disk.x86_64                           2.7.161220-4756                @ntop    
nbox.noarch                             2.5.0-553                      @ntop-noarch
nprobe.x86_64                           7.5.161220-5542                @ntop    
ntopng.x86_64                           2.5.161220-1929                @ntop    
ntopng-data.noarch                      2.5.161220-1929                @ntop-noarch
pfring.x86_64                           6.5.0-1065                     @ntop    
pfring-dkms.noarch                      6.5.0-1065                     @ntop-noarch
pfring-drivers-zc-dkms.noarch           1.2-0                          @ntop-noarch
cento.x86_64                            1.3.161221-163                 ntop     
e1000e-zc.noarch                        3.2.7.1.1068-dkms              ntop-noarch
fm10k-zc.noarch                         0.20.1.1068-dkms               ntop-noarch
fontopia.x86_64                         1.7-1.el7                      epel     
igb-zc.noarch                           5.3.3.5.1068-dkms              ntop-noarch
n2disk.x86_64                           2.7.161221-4756                ntop     
nprobe.x86_64                           7.5.161221-5542                ntop     
nprobes.x86_64                          7.5.161221-5542                ntop     
nscrub.x86_64                           0.99.161221-403                ntop     
ntopng.x86_64                           2.5.161221-1934                ntop     
ntopng-data.noarch                      2.5.161221-1934                ntop-noarch
pfring.x86_64                           6.5.0-1068                     ntop     
pfring-dkms.noarch                      6.5.0-1068                     ntop-noarch

**Comment by simonemainardi** [comment]
what is the load of the interface? If it is close to 10 Gbps, I would recommend using RSS=4 with zero copy. You said you've already tried. Can you please report drop statistics w/ and w/o RSS enabled?

Also make sure to restart pfring after changing RSS and check under /proc/net/pf_ring/dev/<device name>/info to confirm that changes have taken effect.

**Comment by papage** [comment]
Well it is about 2G.

How do i disable RSS?

Sp

pfcount -i zc:ens160
Absolute Stats: [1'698'954 pkts total][0 pkts dropped][0.0% dropped]
[1'698'954 pkts rcvd][1'468'030'264 bytes rcvd][283'139.13 pkt/sec][1'957.23 Mbit/sec]
=========================
Actual Stats: [258'731 pkts rcvd][1'000.06 ms][258'713.14 pps][1.87 Gbps]

**Comment by simonemainardi** [comment]
please refer to this document https://github.com/ntop/PF_RING/blob/dev/doc/README.RSS.md

**Comment by papage** [comment]
I did change to RSS=4,4,4,4 and disabled the DNS queries and now The results look better:
Queue zc:ens160@0 has about 24% loss and the rest of the qeues have about 5% loss.,

Ntopng is at about 300% CPU.

In ntopng, each queue seems to display results but the 'view' that combines them all displays nothing:
--interface=view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3
Is there anything wrong with the view?

Sp

**Comment by simonemainardi** [comment]
please paste ntopng output or console log.

I also noticed that you are using a big /16 local network. How many local hosts do you have? Reducing the number of local hosts -- for example by partitioning the bing/16 into smaller subnetwork -- will have for sure a positive impact on the performances.

**Comment by papage** [comment]
Hi,

Ntopng show about 7K devices, 50K hosts (i guess remote ones are included).
Where can  i see the ntopng output?

Also ntopng reports all foreign hosts as having the router mac address (I can see the logic in that). 

Meanwhile, I can see this error messages on /var/log/messages:
Dec 22 14:14:01 tomati systemd: Started Start/stop ntopng program.
Dec 22 14:14:02 tomati ntopng: [PF_RINGInterface.cpp:71] WARNING: Unable to set packet capture direction
Dec 22 14:14:02 tomati ZC[3216]: error opening /dev/hugepages/ens160@3-txrx: Permission denied
Dec 22 14:14:02 tomati ZC[3216]: error mmap'ing 49 hugepages of 2048 KB
Dec 22 14:14:02 tomati ZC[3216]: error opening /dev/hugepages/ens160@2-txrx: Permission denied
Dec 22 14:14:02 tomati ZC[3216]: error mmap'ing 49 hugepages of 2048 KB
Dec 22 14:14:03 tomati ZC[3216]: error opening /dev/hugepages/ens160@0-txrx: Permission denied
Dec 22 14:14:03 tomati ZC[3216]: error mmap'ing 49 hugepages of 2048 KB
Dec 22 14:14:03 tomati ZC[3216]: error opening /dev/hugepages/ens160@1-txrx: Permission denied
Dec 22 14:14:03 tomati ZC[3216]: error mmap'ing 49 hugepages of 2048 KB

while huge pages are mounted on /mnt/huge
# grep Hugepagesize /proc/meminfo
Hugepagesize:       2048 kB
# grep HugePages_Total /proc/meminfo
HugePages_Total:    1024

I 'll try to partition the addres space, to see if there is any perofmance difference.

Sp

**Comment by cardigliano** [comment]
Any update on this?
As of hugepages, /mnt/huge has been changed to /dev/hugepages, which is the default on most OSs now (taht was causing your issue)
Please reopen if necessary.
