### ISSUE TITLE
pf_ring do not work

### ISSUE THREAD

**Issue by FOSquare** [ntop/PF_RING#345]
Hello. i am using the package to install pf_ring. my systme is "Debian GNU/LInux 8 \n \l". I already add the license for eth3.
I make the configurations as shown in the guide. When I type tree /etc/pf_ring/
it shows:
/etc/pf_ring/
├── 001B21B12B7D
├── hugepages.conf
├── interfaces.conf
├── pf_ring.conf
├── pf_ring.start
└── zc
    ├── e1000e
    ├── fm10k
    ├── i40e
    ├── igb
    └── ixgbe
        ├── ixgbe.conf
        └── ixgbe.start
It looks good! However, When I type the command /etc/init.d/pf_ring start. I find no pf_ring in this folder. 

Indeed, I have dual 10Gb/s NICs (eth3 and eth4) on my server. So I need a namespace for the interfaces. When I reboot my server, I need to run a script.sh file to specfy the namespace of the interface. The content of the script.sh is shown below.
"#!/bin/bash
sudo ip netns add 153
sudo ip netns add 154
sudo ip link set dev eth3 netns 153
sudo ip link set dev eth4 netns 154
sudo ip netns exec 153 ip addr add 192.168.0.153/24 dev eth3
sudo ip netns exec 154 ip addr add 192.168.0.154/24 dev eth4
sudo ip netns exec 153 ip link set eth3 up
sudo ip netns exec 154 ip link set eth4 up
"
But then I need to use the command "ip netns exec 153 ifconfig" to show the eth3, and ifconfig will not work.
When I use command ls /proc/net/pf_ring/dev. there is only eth0 and eth1. no eth3 and eth4, while eth3 and eth4 are the 10Gb/s ports I want to use. 
pfcount ip netns exec 153 -i eth3 will shows
pfring_open error [No such device] (pf_ring not loaded or interface eth3 is down ?)

How to solve the namespace of the dual NICs and make the pf_ring works? Thanks a lot!!!

**Comment by FOSquare** [comment]
my eth3 drvier is ixgbe. when I type " ip netns exec 153 ethtool -i eth3" it shows
driver: ixgbe
version: 4.4.6
firmware-version: 0x18b30001
bus-info: 0000:01:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

**Comment by cardigliano** [comment]
Please provide the output of:
cat /proc/net/pf_ring/info
ip netns exec 153 ls /proc/net/pf_ring/dev

**Comment by FOSquare** [comment]
Thanks a lot. Below is the details.

cat /proc/net/pf_ring/info 
PF_RING Version          : 7.0.0 (7.0.0-stable:aa380911521d06acb37032459450d39fea4cdd7e)
Total rings              : 4

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

ls /proc/net/pf_ring/dev
dummy0    eth0  eth1  lo

sudo ip netns exec 153 ls /proc/net/pf_ring/dev
ls: cannot access /proc/net/pf_ring/dev: No such file or directory

 ifconfig
eth0      Link encap:Ethernet  HWaddr 00:26:b9:75:60:8d  
          inet addr:131.155.34.212  Bcast:131.155.35.255  Mask:255.255.254.0
          inet6 addr: fe80::226:b9ff:fe75:608d/64 Scope:Link
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1
          RX packets:1965458 errors:0 dropped:0 overruns:0 frame:0
          TX packets:27167 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:213878835 (203.9 MiB)  TX bytes:3055813 (2.9 MiB)

eth1      Link encap:Ethernet  HWaddr 00:26:b9:75:60:8e  
          UP BROADCAST PROMISC MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING PROMISC  MTU:65536  Metric:1
          RX packets:1562713 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1562713 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:175970075 (167.8 MiB)  TX bytes:175970075 (167.8 MiB)

root@krdevdb:/home# ip netns exec 153 ifconfig
eth3      Link encap:Ethernet  HWaddr 00:1b:21:98:98:e4  
          inet addr:192.168.0.153  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::21b:21ff:fe98:98e4/64 Scope:Link
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1
          RX packets:64746716 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30731678 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:97711655160 (91.0 GiB)  TX bytes:2029508804 (1.8 GiB)

root@krdevdb:/home# ip netns exec 154 ifconfig
eth4      Link encap:Ethernet  HWaddr 00:1b:21:98:98:e5  
          inet addr:192.168.0.154  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::21b:21ff:fe98:98e5/64 Scope:Link
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:43 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:6600 (6.4 KiB)

Thanks a lot.

**Comment by FOSquare** [comment]
Sorry for the issue. I tried ip netns exec 153 pfcount -i eth3, and it works. before what I typed is "pfcount ip netns exec 153 -i eth3", pfcount should be just before -i eth3, rather at the begining. 
However, when I use  ip netns exec 153 pfcount -i zc:eth3, it still do not work. And it shows
"pfring_open error [no such device] (pf_ring not loaded or interface zc:eth3 is down ?)"
I guess pf_ring zc drive is not correct down load or configrated?
Thanks a lot for your help.

**Comment by cardigliano** [comment]
Please use latest dev packages as we pushed many fixes for namespaces (a new stable will be released soon)

**Comment by FOSquare** [comment]
Thanks a lot. The latest dev package, do you mean the newest version of Debian 8 jessie? 
I will try the newest version of (Debian 8 jessie). If I still have problems, I will come back to you.  Thanks again.

**Comment by cardigliano** [comment]
I mean you should select the "nightly builds" repo from http://packages.ntop.org

**Comment by FOSquare** [comment]
yes, I am tryiing, I just found I express wronly. I means I will try the newest pf_ring version for debian 8. :)
 Thanks a lot.

**Comment by FOSquare** [comment]
I removed the package. and installed the nightly builds. but  still When I type the command /etc/init.d/pf_ring start. I find no pf_ring in this folder.
ip netns exec 153 pf_count -i eth3 works, 
but ip netns exec 153 pf_count -i zc:eth3 do not work. and it shows
"pfring_open error [No such device] (pf_ring not loaded or interface zc:eth3 is down?)" 
----------------------------------------------

cat /proc/net/pf_ring/info  will shows
PF_RING Version          : 7.1.0 (dev:9c0d8cec1de73bfeb6206f8397382aa33a29adeb)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 17
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0 

ip netns exec 153 ls /proc/net/pf_ring/dev will show
eth3  lo

Thanks a lot.

**Comment by cardigliano** [comment]
Please provide:
ip netns exec 153 cat /proc/net/pf_ring/dev/eth3/info

**Comment by FOSquare** [comment]
ip netns exec 153 cat /proc/net/pf_ring/dev/eth3/info
Name:         eth3
Index:        4
Address:      00:1B:21:98:98:E4
Polling Mode: NAPI
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  0
TX Queues:    4
RX Queues:    4

Polling mode is not ZC:NAPI.

From the instructions. I found that 
Example loading PF_RING and the ixgbe-ZC driver:
cd <PF_RING PATH>/kernel
insmod pf_ring.ko
cd PF_RING/drivers/intel/ixgbe/ixgbe-X.X.X-zc/src
make
./load_driver.sh

I can not find the <PF_RING PATH>. "whereis PF_RING" do not tell. I intslled from nighly packages.

Thanks a  lot.

**Comment by cardigliano** [comment]
Please follow the instructions at http://www.ntop.org/guides/pf_ring/get_started/packages_installation.html

**Comment by FOSquare** [comment]
I do follow the instructions. When I type "/etc/init.d/pf_ring start" , It shows, 
"~bash: / /etc/init.d/pf_ring: No such file or directroy"
Then I type "systemctl start pf_ring" Nothing shows. 

ip netns exec 153 cat /proc/net/pf_ring/dev/eth1/info | grep ZC  to check the zc driver. it shows nothing. 
While ip netns exec 153 cat /proc/net/pf_ring/dev/eth1/info shows:
Name: eth3
Index: 4
Address: 00:1B:21:98:98:E4
Polling Mode: NAPI
Type: Ethernet
Family: Standard NIC
#Bound Sockets: 0
TX Queues: 4
RX Queues: 4

I also run sudo touch /etc/pf_ring/forcestart
and configure 
MANAGEMENT_INTERFACES="eth1"
CAPTURE_INTERFACES="eth3 eth4"

I think the zc driver is not loaded since I do not find pf_ring form this command "/etc/init.d/pf_ring start"

Thanks a lot.

**Comment by cardigliano** [comment]
Please run:
systemctl restart pf_ring
systemctl status pf_ring

**Comment by FOSquare** [comment]
root@krdevdb:~# systemctl restart pf_ring
root@krdevdb:~# systemctl status pf_ring
● pf_ring.service - Start/stop pfring service
   Loaded: loaded (/etc/systemd/system/pf_ring.service; enabled)
   Active: active (exited) since Fri 2018-06-01 08:34:55 CEST; 18s ago
  Process: 3805 ExecStop=/usr/local/bin/pf_ringctl stop (code=exited, status=0/SUCCESS)
  Process: 3871 ExecStart=/usr/local/bin/pf_ringctl start (code=exited, status=0/SUCCESS)
 Main PID: 3871 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/pf_ring.service

Jun 01 08:34:55 krdevdb pf_ringctl[3871]: Starting PF_RING module:.
Jun 01 08:34:55 krdevdb systemd[1]: Started Start/stop pfring service.

Thanks a lot

**Comment by cardigliano** [comment]
Did you create configuration files for i40e according to http://www.ntop.org/guides/pf_ring/get_started/packages_installation.html ?
Please check that you have /etc/pf_ring/zc/i40e/i40e{.conf, .start}

**Comment by FOSquare** [comment]
Thanks a lot.
When I check  /etc/pf_ring/zc/i40e/..., it is empty under this folder "/etc/pf_ring/zc/i40e/...".
But tree /etc/pf_ring/ it shows:
/etc/pf_ring/
├── 001B21B12B7D
├── hugepages.conf
├── interfaces.conf
├── pf_ring.conf
├── pf_ring.start
└── zc
├── e1000e
├── fm10k
├── i40e
├── igb
└── ixgbe
├── ixgbe.conf
└── ixgbe.start

And ip netns exec 153 cat /proc/net/pf_ring/dev/eth1/info | grep ZC will show
Polling Mode:      ZC/NAPI

And when I type ip netns exec 153 pfcount -i zc:eth3
it show normal as without zc as time changes (0 packet are captured since I do not generate traffic yet).
However, when I use iperf -s and iperf -c to generate traffic between those two server. The server with the pf_ring zc running will be stuck. And I need to reboot the server.
And  ip netns exec 153 pfcount -i eth3 works very good with iperf test. the bandwidth is around 5 Gb/s.

What should I do with pf_ring zc?

**Comment by cardigliano** [comment]
@FOSquare please note that you cannot run ZC on a management interface, as it disconnects the interface from the system (it is a kernel-bypass technology)
