### ISSUE TITLE
zbalance_ipc stripping IP headers

### ISSUE THREAD

**Issue by patrickstjohn** [ntop/PF_RING#356]
We have dozens of PF_RING deployments and this is the first time running into this. I'm at a bit of a loss what could be causing this effect but believe I have it narrowed down to zbalance_ipc. Here is what's going on:

Kernel: 4.16.13-1.el7.elrepo.x86_64
PF_RING: pfring-7.3.0-2000.x86_64.rpm, pfring-dkms-7.3.0-2000.noarch.rpm
Drivers: ixgbe-zc-5.3.7.2000-dkms.noarch.rpm

zbalance_ipc command: 
```
/usr/bin/zbalance_ipc -i zc:p4p1,zc:p4p2 -c 98 -n 5,1 -m 1 -S 15 -g 13 -r 0:dummy0 -r 1:dummy1 -r 2:dummy2 -r 3:dummy3 -r 4:dummy4 -r 5:dummy32 -l /var/log/zbalance1.log -d -u /dev/hugepages
```

tcpdump -i dummy32
```
13:01:26.604972 00:00:00:00:00:00 (oui Ethernet) > 00:00:00:00:00:00 (oui Ethernet) Null Information, send seq 0, rcv seq 0, Flags [Command], length 1304
	0x0000:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0030:  0000 0007 b403 e802 246e 96ad a1c4 8100  ........$n......
```

If you end up  killing zbalance_ipc and listening on p4p1/p4p2 directly the full packet with all the headers comes through as expected and all our protocol parsing works properly. The hardware and configuration is identical for the previous deployments (everything is deployed via Ansible) this deployment is just updated from the 7.1 branch to the 7.3 branch.

**Comment by cardigliano** [comment]
@patrickstjohn this seems to be related to a bug with the ixgbe zc driver when receiving packets in burst mode, we already pushed a fix on github, new packages will be available in 1h. The bug was introduced a few days ago, please confirm if it is fixed. Thank you.

**Comment by patrickstjohn** [comment]
@cardigliano Fantastic! As soon as I see the packages in the repository I'll push to our sensor and update this.

**Comment by patrickstjohn** [comment]
I noticed a newer build (2001) and attempted that. Not sure if that is a holdover from a nightly or if that's the new build. Still getting the same error with the following driver:

```
filename:       /lib/modules/4.16.13-1.el7.elrepo.x86_64/extra/ixgbe_zc.ko
version:        5.3.7
license:        GPL
description:    Intel(R) 10GbE PCI Express Linux Network Driver
author:         Intel Corporation, <linux.nics@intel.com>
srcversion:     FD932BE5C594D8F5AA6C364
```

I'll keep an eye out on if a new build pops through.

**Comment by cardigliano** [comment]
That's not the correct one, it's still building..

**Comment by patrickstjohn** [comment]
@cardigliano Added build 2003 and all is right with the world. Packet headers are in place and we're back capturing traffic. Really appreciate kicking off that build to roll the fix in.
