### ISSUE TITLE
pfring-dkms will not update after update to ntopng v.3.4.180726 on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Kaldek** [ntop/PF_RING#388]
running apt upgrade on ubuntu server this morning included an update for ntopng.  The upgrade errored out regarding pf_ring-dkms:

```console
Preparing to unpack .../pfring-dkms_7.2.0_all.deb ...
Unpacking pfring-dkms (7.2.0) over (7.2.0) ...
dpkg: dependency problems prevent configuration of pfring-dkms:
 pfring-dkms depends on pfring (= 7.2.0-2083); however:
  Version of pfring on system is 7.2.0-2095.

dpkg: error processing package pfring-dkms (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 pfring-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by cardigliano** [comment]
Hi @Kaldek, it seems this is working in our lab on the same OS, please try with apt-get update again to check if you are still able to reproduce this with the latest repo update.

**Comment by Kaldek** [comment]
Hi @cardigliano no it's still having the same issue even after "sudo apt update".  I can uninstall pfring-dkms so that apt keeps working but I can't get all the ducks to line up.  I could manually remove everything and then start by installing pfring 7.2.0-2083 but then ntopng will just try to uplift it to 7.2.0-2095:

```shell
sudo apt remove pfring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 ntopng : Depends: pfring (= 7.2.0-2095) but it is not going to be installed
 pfring-dkms : Depends: pfring (= 7.2.0-2083) but it is not going to be installed
```

**Comment by Kaldek** [comment]
A bit more info on the state of pfring-dkms and pfring when they are both installed:

```bash
sudo apt list pfring-dkms -a
Listing... Done
pfring-dkms/unknown 7.2.0 all [upgradable from: 7.2.0]
pfring-dkms/now 7.2.0 all [installed,upgradable to: 7.2.0]

sudo apt list pfring
Listing... Done
pfring/unknown,now 7.2.0-2095 amd64 [installed,automatic]

sudo apt list --upgradable
Listing... Done
pfring-dkms/unknown 7.2.0 all [upgradable from: 7.2.0]

sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 pfring-dkms : Depends: pfring (= 7.2.0-2083) but 7.2.0-2095 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by Kaldek** [comment]
A bit of info on the repos I'm using (note: Zabbix was added after the pf_ring issues started so can be discounted as involved):

```shell
sudo apt update
Ign:1 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 InRelease
Hit:2 http://repo.zabbix.com/zabbix/3.4/ubuntu bionic InRelease                                                                                                    
Hit:3 http://dl.ubnt.com/unifi/debian unifi-5.6 InRelease                                                                                                          
Hit:4 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 Release                                                                                   
Hit:5 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease                                                                     
Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                         
Hit:6 http://dl.ubnt.com/unifi/debian stable InRelease                                                                    
Get:9 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]                                                                                 
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                                                                         
Hit:11 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease                                                                      
Hit:12 http://packages.ntop.org/apt-stable/18.04 x64/ InRelease                                                                                     
Hit:13 http://packages.ntop.org/apt-stable/18.04 all/ InRelease                        
Get:14 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
```

**Comment by cardigliano** [comment]
Please check the .deb info below on my system, it is strange that you have a dependency to pfring = 7.2.0-2083. I pushed a repo refresh right now anyway (available in 30m).

# dpkg -I /var/cache/apt/archives/pfring-dkms_7.2.0_all.deb
 new Debian package, version 2.0.
 size 64936 bytes: control archive=1780 bytes.
     333 bytes,     9 lines      control              
    1391 bytes,    17 lines      md5sums              
    1217 bytes,    49 lines   *  postinst             #!/bin/sh
     335 bytes,    28 lines   *  prerm                #!/bin/sh
 Package: pfring-dkms
 Version: 7.2.0
 Architecture: all
 Maintainer: Luca Deri <deri@ntop.org>
 Installed-Size: 335
 Depends: pfring (= 7.2.0-2095), dkms (>= 1.95)
 Section: free
 Priority: optional
 Description: PF_RING driver in DKMS format. GIT info: 7.2.0-stable:d93fee74cad95f66202ce138cf13afc8b07bb419 (Sat Aug 11 19:45:30 2018 +0200)

**Comment by Kaldek** [comment]
Here's the output of dpkg:

```shell
sudo dpkg -I /var/cache/apt/archives/pfring-dkms_7.2.0_all.deb

 new Debian package, version 2.0.
 size 64936 bytes: control archive=1780 bytes.
     333 bytes,     9 lines      control              
    1391 bytes,    17 lines      md5sums              
    1217 bytes,    49 lines   *  postinst             #!/bin/sh
     335 bytes,    28 lines   *  prerm                #!/bin/sh
 Package: pfring-dkms
 Version: 7.2.0
 Architecture: all
 Maintainer: Luca Deri <deri@ntop.org>
 Installed-Size: 335
 Depends: pfring (= 7.2.0-2083), dkms (>= 1.95)
 Section: free
 Priority: optional
 Description: PF_RING driver in DKMS format. GIT info: 7.2.0-stable:f44a9c861392e03f628854c0e3f875dbe1f8de18 (Wed Jul 25 16:25:19 2018 +0200)
```

**Comment by Kaldek** [comment]
Your repo refresh fixed it.  No issues at all now.

**Comment by malvinas2** [comment]
Same issue here: Version of pfring is 7.2.0-2113, but pfring-dkms expects 7.2.0-2018

Ubuntu 16.04.5 LTS

```
root@ubuntu:~# dpkg -I /var/cache/apt/archives/pfring-dkms_7.2.0_all.deb
 neues Debian-Paket, Version 2.0.
 Größe 64952 Byte: control-Archiv= 1752 Byte.
     333 Byte,     9 Zeilen      control
    1391 Byte,    17 Zeilen      md5sums
    1217 Byte,    49 Zeilen   *  postinst             #!/bin/sh
     335 Byte,    28 Zeilen   *  prerm                #!/bin/sh
 Package: pfring-dkms
 Version: 7.2.0
 Architecture: all
 Maintainer: Luca Deri <deri@ntop.org>
 Installed-Size: 335
 Depends: pfring (= 7.2.0-2108), dkms (>= 1.95)
 Section: free
 Priority: optional
 Description: PF_RING driver in DKMS format. GIT info: 7.2.0-stable:758f764cf6243c81d61d7b6d7cd1ccee04aaa1b6 (Wed Aug 22 15:42:35 2018 +0200)
```
```
root@ubuntu:~# apt-get -f install
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Abhängigkeiten werden korrigiert ... Fertig
Die folgenden zusätzlichen Pakete werden Installiert
  pfring-dkms
Die folgenden Pakete werden aktualisiert (Upgrade):
  pfring-dkms
1 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
1 nicht vollständig installiert oder entfernt.
Es müssen noch 0 B von 65,0 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] J
(Lese Datenbank ... 191698 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../pfring-dkms_7.2.0_all.deb ...
Entpacken von pfring-dkms (7.2.0) über (7.2.0) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von pfring-dkms:
 pfring-dkms hängt ab von pfring (= 7.2.0-2108); aber:
  Version von pfring auf dem System ist 7.2.0-2113.

dpkg: Fehler beim Bearbeiten des Paketes pfring-dkms (--configure):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Es wurde kein Apport-Bericht verfasst, da die Fehlermeldung darauf hindeutet, dass dies lediglich ein Folgefehler eines vorherigen Problems ist.
 Fehler traten auf beim Bearbeiten von:
 pfring-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Used repos: 
```
deb http://packages.ntop.org/apt-stable/16.04/ x64/
deb http://packages.ntop.org/apt-stable/16.04/ all/
```

**Comment by cardigliano** [comment]
@malvinas2 it could be it was in the middle of a repo update,  could you try updating again?
This is the pfring-dkms dep in the latest package:
Depends: pfring (= 7.2.0-2113), dkms (>= 1.95)

**Comment by malvinas2** [comment]
A simple update and upgrade didn't work. 
I downloaded manually the newest *.deb
`wget http://packages.ntop.org/apt-stable/16.04/all/pfring-dkms_7.2.0_all.deb`
and installed it
`dpkg -i pfring-dkms_7.2.0_all.deb`
Everything is working fine now. Thanks for your help!

**Comment by cardigliano** [comment]
This is working with an update/upgrade in our lab, not sure why a manual download was needed in your case. Please reopen in case.

**Comment by nrohluap** [comment]
Just ran into this same dependency issue on Ubuntu 18.04.3 LTS.

 pfring-dkms depends on pfring (= 7.4.0-2604); however:
  Version of pfring on system is 7.4.0-2612.

Manually pulled/installed pfring-dkms_7.4.0 and that solved the issue.

**Comment by cardigliano** [comment]
@nrohluap it seems to be working for me, however I pushed a repo refresh (it should complete in ~1h), please try updating again and let me know. Thank you.

**Comment by ghost** [comment]
I am also having this issue tried a few apt-get updates but it still won't work with the error. 

The following packages have unmet dependencies:
 pfring-dkms : Depends: pfring (= 7.4.0-2643) but 7.4.0-2658 is installed

**Comment by cardigliano** [comment]
@Wilsonfromdevon I just tried updating my ubuntu 18 box and it worked smootly.. could you try again with "apt-get clean all && apt-get update && apt-get upgrade" please?

# apt list pfring
pfring/unknown,now 7.4.0-2658 amd64 [installed]
# apt list pfring-dkms
pfring-dkms/unknown,now 7.4.0 all [installed]
