### ISSUE TITLE
kernel panic when parse  Ethernet frame with 802.1Q tag, but frame length only 64 bytes

### ISSUE THREAD

**Issue by Ivlyth** [ntop/PF_RING#523]
kernel panic log:
```
[974431.832901] Kernel panic - not syncing: stack-protector: Kernel stack is corrupted in: ffffffffc0b749c0

[974431.833999] CPU: 21 PID: 0 Comm: swapper/21 Kdump: loaded Tainted: G           OE  ------------   3.10.0-957.1.3.el7.x86_64 #1
[974431.835340] Hardware name: Supermicro Super Server/X10DRL-LN4, BIOS 2.0a 04/28/2017
[974431.836025] Call Trace:
[974431.836623]  <IRQ>  [<ffffffffa8561e41>] dump_stack+0x19/0x1b
[974431.837289]  [<ffffffffa855b550>] panic+0xe8/0x21f
[974431.837893]  [<ffffffffc0b749c0>] ? parse_pkt.isra.29+0x2a0/0x2a0 [pf_ring]
[974431.838483]  [<ffffffffa7e973bb>] __stack_chk_fail+0x1b/0x20
[974431.839130]  [<ffffffffc0b749c0>] parse_pkt.isra.29+0x2a0/0x2a0 [pf_ring]
[974431.839775]  [<ffffffffc0b7904c>] skb_ring_handler+0x76c/0x1ee0 [pf_ring]
[974431.840465]  [<ffffffffc0b7991c>] ? skb_ring_handler+0x103c/0x1ee0 [pf_ring]
[974431.841167]  [<ffffffffa7f4a6d5>] ? handle_irq_event_percpu+0x55/0x80
[974431.841848]  [<ffffffffa7e2e554>] ? handle_irq+0xe4/0x1a0
[974431.842574]  [<ffffffffc0b7a855>] packet_rcv+0x95/0xb0 [pf_ring]
[974431.843368]  [<ffffffffa84235aa>] ? kfree_skb+0x3a/0xa0
[974431.844102]  [<ffffffffa8438f78>] __netif_receive_skb_core+0x128/0xa10
[974431.844792]  [<ffffffffa84b6d00>] ? udp4_gro_receive+0x130/0x2a0
[974431.845497]  [<ffffffffa8439878>] __netif_receive_skb+0x18/0x60
[974431.846246]  [<ffffffffa8439900>] netif_receive_skb_internal+0x40/0xc0
[974431.847027]  [<ffffffffa843a588>] napi_gro_receive+0xd8/0x100
[974431.847939]  [<ffffffffc04aba26>] igb_clean_rx_irq+0x356/0x800 [igb]
[974431.848848]  [<ffffffffc04ac263>] igb_poll+0x393/0x770 [igb]
[974431.849738]  [<ffffffffa8439f1f>] net_rx_action+0x26f/0x390
[974431.850534]  [<ffffffffa7ea0f05>] __do_softirq+0xf5/0x280
[974431.850538]  [<ffffffffa857832c>] call_softirq+0x1c/0x30
[974431.850541]  [<ffffffffa7e2e675>] do_softirq+0x65/0xa0
[974431.850543]  [<ffffffffa7ea1285>] irq_exit+0x105/0x110
[974431.850548]  [<ffffffffa85795e6>] do_IRQ+0x56/0xf0
[974431.850554]  [<ffffffffa856b362>] common_interrupt+0x162/0x162
[974431.850566]  <EOI>  [<ffffffffa83ae227>] ? cpuidle_enter_state+0x57/0xd0
[974431.850569]  [<ffffffffa83ae37e>] cpuidle_idle_call+0xde/0x230
[974431.850573]  [<ffffffffa7e366de>] arch_cpu_idle+0xe/0xc0
[974431.850580]  [<ffffffffa7efc49a>] cpu_startup_entry+0x14a/0x1e0
[974431.850586]  [<ffffffffa7e57db7>] start_secondary+0x1f7/0x270
[974431.850591]  [<ffffffffa7e000d5>] start_cpu+0x5/0x14
```

invalid packet (remove .log suffix): 
[one-64.pcap.log](https://github.com/ntop/PF_RING/files/3762326/one-64.pcap.log)

if i use bro with PF_RING enabled, and sniff packet from NIC ,  if this packet show in the traffic,  kernel MUST be panic.  

My OS is: centos-7.4.1708
kernel version is: 3.10.0-957.1.3.el7.x86_64
CPU:
```
[root@prs-sensor 127.0.0.1-2019-10-23-19:36:52]# lshw -c cpu
  *-cpu:0
       description: CPU
       product: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
       vendor: Intel Corp.
       vendor_id: GenuineIntel
       physical id: 30
       bus info: cpu@0
       version: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
       slot: CPU1
       size: 1230MHz
       capacity: 4GHz
       width: 64 bits
       clock: 100MHz
       capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts cpufreq
       configuration: cores=8 enabledcores=8 threads=16
  *-cpu:1
       description: CPU
       product: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
       vendor: Intel Corp.
       vendor_id: GenuineIntel
       physical id: 34
       bus info: cpu@1
       version: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
       slot: CPU2
       size: 1200MHz
       capacity: 4GHz
       width: 64 bits
       clock: 100MHz
       capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts cpufreq
       configuration: cores=8 enabledcores=8 threads=16
```
NIC:
```
*-network:3
       description: Ethernet interface
       product: I350 Gigabit Network Connection
       vendor: Intel Corporation
       physical id: 0.3
       bus info: pci@0000:03:00.3
       logical name: eno4
       version: 01
       serial: ac:1f:6b:61:19:3f
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=igb driverversion=5.4.0-k firmware=1.63, 0x800009fa ip=192.168.0.3 latency=0 link=no multicast=yes port=twisted pair
       resources: irq:68 memory:c7100000-c711ffff ioport:6000(size=32) memory:c7180000-c7183fff memory:900c0000-900dffff memory:900e0000-900fffff
```

**Comment by Ivlyth** [comment]
It looks the same issue here: https://lists.gt.net/ntop/misc/46690

**Comment by cardigliano** [comment]
What PF_RING version are you running?
cat /proc/net/pf_ring/info | grep Version

**Comment by Ivlyth** [comment]
6.4.0

**Comment by cardigliano** [comment]
@MythRen it is likely that issue has been already fixed, latest stable is 7.4. Please update.

**Comment by Ivlyth** [comment]
@cardigliano i update pfring to 7.4.0, (but /proc/net/pf_ring/info show is 7.5.0), also cause kernel panic.  

and i update kernel to 3.10.0-1062.4.1.el7.x86_64 but the issue still exists。

panic log:
```
[ 1005.669284] Kernel panic - not syncing: stack-protector: Kernel stack is corrupted in: ffffffffc08184d2

[ 1005.669380] CPU: 18 PID: 0 Comm: swapper/18 Kdump: loaded Tainted: G           OE  ------------   3.10.0-1062.4.1.el7.x86_64 #1
[ 1005.669465] Hardware name: Supermicro Super Server/X10DRL-LN4, BIOS 2.0a 04/28/2017
[ 1005.669522] Call Trace:
[ 1005.669547]  <IRQ>  [<ffffffffab978ba4>] dump_stack+0x19/0x1b
[ 1005.669612]  [<ffffffffab972947>] panic+0xe8/0x21f
[ 1005.669666]  [<ffffffffab8378a2>] ? skb_copy_bits+0x62/0x2c0
[ 1005.669702]  [<ffffffffc08184d2>] ? parse_pkt.isra.32+0x3c2/0x3d0 [pf_ring]
[ 1005.669744]  [<ffffffffab29a6cb>] __stack_chk_fail+0x1b/0x20
[ 1005.669779]  [<ffffffffc08184d2>] parse_pkt.isra.32+0x3c2/0x3d0 [pf_ring]
[ 1005.669819]  [<ffffffffab2d2180>] ? task_rq_unlock+0x20/0x20
[ 1005.669854]  [<ffffffffc081da8f>] skb_ring_handler+0x6bf/0x1980 [pf_ring]
[ 1005.669894]  [<ffffffffab959439>] ? vlan_gro_receive+0xf9/0x150
[ 1005.669929]  [<ffffffffab959439>] ? vlan_gro_receive+0xf9/0x150
[ 1005.669964]  [<ffffffffab959439>] ? vlan_gro_receive+0xf9/0x150
[ 1005.669999]  [<ffffffffab959439>] ? vlan_gro_receive+0xf9/0x150
[ 1005.671256]  [<ffffffffc081ed8e>] packet_rcv+0x3e/0x70 [pf_ring]
[ 1005.672558]  [<ffffffffab84d5d8>] __netif_receive_skb_core+0x128/0xa10
[ 1005.673872]  [<ffffffffab84ded8>] __netif_receive_skb+0x18/0x60
[ 1005.675197]  [<ffffffffab84df60>] netif_receive_skb_internal+0x40/0xc0
[ 1005.676510]  [<ffffffffab84ebe8>] napi_gro_receive+0xd8/0x100
[ 1005.677813]  [<ffffffffc01cfb36>] igb_clean_rx_irq+0x356/0x800 [igb]
[ 1005.679084]  [<ffffffffc01d037b>] igb_poll+0x39b/0x790 [igb]
[ 1005.680354]  [<ffffffffab2d26e1>] ? __wake_up_common_lock+0x91/0xc0
[ 1005.681604]  [<ffffffffab84e57f>] net_rx_action+0x26f/0x390
[ 1005.682823]  [<ffffffffab2a42c5>] __do_softirq+0xf5/0x280
[ 1005.684041]  [<ffffffffab98f42c>] call_softirq+0x1c/0x30
[ 1005.685265]  [<ffffffffab22f715>] do_softirq+0x65/0xa0
[ 1005.686488]  [<ffffffffab2a4645>] irq_exit+0x105/0x110
[ 1005.687688]  [<ffffffffab990886>] do_IRQ+0x56/0xf0
[ 1005.688908]  [<ffffffffab98236a>] common_interrupt+0x16a/0x16a
[ 1005.690116]  <EOI>  [<ffffffffab7c0057>] ? cpuidle_enter_state+0x57/0xd0
[ 1005.691304]  [<ffffffffab7c01ae>] cpuidle_idle_call+0xde/0x230
[ 1005.692508]  [<ffffffffab237c6e>] arch_cpu_idle+0xe/0xc0
[ 1005.693720]  [<ffffffffab2ffcfa>] cpu_startup_entry+0x14a/0x1e0
[ 1005.694924]  [<ffffffffab259d77>] start_secondary+0x1f7/0x270
[ 1005.696137]  [<ffffffffab2000d5>] start_cpu+0x5/0x14
```

**Comment by Ivlyth** [comment]
centos 8 with PF-RING latest dev branch also cause kernel panic:

test with pfcount

```
[ 9972.603334] Kernel panic - not syncing: stack-protector: Kernel stack is corrupted in: parse_pkt.constprop.52+0x272/0x280 [pf_ring]

[ 9972.605026] CPU: 0 PID: 0 Comm: swapper/0 Kdump: loaded Tainted: G           OE    --------- -  - 4.18.0-80.el8.x86_64 #1
[ 9972.605826] Hardware name: Supermicro Super Server/X10DRL-LN4, BIOS 2.0a 04/28/2017
[ 9972.606681] Call Trace:
[ 9972.607548]  <IRQ>
[ 9972.608370]  dump_stack+0x5c/0x80
[ 9972.609230]  panic+0xe7/0x247
[ 9972.610040]  ? parse_pkt.constprop.52+0x272/0x280 [pf_ring]
[ 9972.610972]  __stack_chk_fail+0x15/0x20
[ 9972.611892]  parse_pkt.constprop.52+0x272/0x280 [pf_ring]
[ 9972.612741]  ? copy_data_to_ring+0x378/0x680 [pf_ring]
[ 9972.613656]  pf_ring_skb_ring_handler+0x2ec/0x1080 [pf_ring]
[ 9972.614490]  ? vlan_gro_receive+0xef/0x170
[ 9972.615382]  ? vlan_gro_receive+0xef/0x170
[ 9972.616239]  ? vlan_gro_receive+0xef/0x170
[ 9972.617038]  ? packet_rcv+0x51/0x60 [pf_ring]
[ 9972.617865]  packet_rcv+0x51/0x60 [pf_ring]
[ 9972.618674]  __netif_receive_skb_core+0x2df/0xbe0
[ 9972.619554]  ? vlan_gro_receive+0xef/0x170
[ 9972.620398]  ? vlan_gro_receive+0xef/0x170
[ 9972.621255]  netif_receive_skb_internal+0x42/0xf0
[ 9972.622035]  napi_gro_receive+0xba/0xe0
[ 9972.622813]  igb_clean_rx_irq+0x320/0x850 [igb]
[ 9972.623625]  igb_poll+0x587/0x7a0 [igb]
[ 9972.624480]  net_rx_action+0x149/0x3a0
[ 9972.625240]  __do_softirq+0xe4/0x2f8
[ 9972.625966]  irq_exit+0xf7/0x100
[ 9972.626736]  do_IRQ+0x85/0xd0
[ 9972.627551]  common_interrupt+0xf/0xf
[ 9972.628303]  </IRQ>
[ 9972.629097] RIP: 0010:cpuidle_enter_state+0xb7/0x2a0
[ 9972.629959] Code: e8 4e 67 a7 ff 80 7c 24 03 00 74 17 9c 58 0f 1f 44 00 00 f6 c4 02 0f 85 d7 01 00 00 31 ff e8 60 2a ad ff fb 66 0f 1f 44 00 00 <48> b8 ff ff ff ff f3 01 00 00 4c 29 f3 ba ff ff ff 7f 48 39 c3 7f
[ 9972.630786] RSP: 0018:ffffffffbca03e78 EFLAGS: 00000246 ORIG_RAX: ffffffffffffffdb
[ 9972.631688] RAX: ffff9f72df823080 RBX: 00000911ed7a8860 RCX: 000000000000001f
[ 9972.632540] RDX: 00000911ed7a8860 RSI: 0000000000000000 RDI: 0000000000000000
[ 9972.633331] RBP: 0000000000000004 R08: 0007c8c2c4b2afd6 R09: 00000000000000a9
[ 9972.634100] R10: 000000000000010b R11: ffff9f72df822028 R12: ffff9f72df82da90
[ 9972.634968] R13: ffffffffbcb23398 R14: 00000911ed79316b R15: 0000000000000000
[ 9972.635790]  ? cpuidle_enter_state+0x92/0x2a0
[ 9972.636589]  do_idle+0x236/0x280
[ 9972.637378]  cpu_startup_entry+0x6f/0x80
[ 9972.638157]  start_kernel+0x530/0x550
[ 9972.638924]  secondary_startup_64+0xb7/0xc0
```

**Comment by cardigliano** [comment]
@MythRen I was unable to reproduce this with your pcap so far, I also tried on Centos 8. What network adapter are you using? (check lspci and ethtool -i <dev>)
Did you try setting on/off the vlan offload to see if it makes any difference? (ethtool -K <dev> rxvlan off)

**Comment by MythRen** [comment]
https://send.firefox.com/download/4f35ecb61e929453/#_BBMH7qkkOhZg9ULv6vNlQ
password is : pfring

**Comment by cardigliano** [comment]
Downloaded. Thank you.

**Comment by Ivlyth** [comment]
```
[root@prs-sensor ~]# ethtool -i eno4
driver: igb
version: 5.4.0-k
firmware-version: 1.63, 0x800009fa
expansion-rom-version:
bus-info: 0000:03:00.3
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
[root@prs-sensor ~]# ethtool -i ens4f1
driver: igb
version: 5.4.0-k
firmware-version: 1.52.0
expansion-rom-version:
bus-info: 0000:82:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
```

```
  *-network:3
       description: Ethernet interface
       product: I350 Gigabit Network Connection
       vendor: Intel Corporation
       physical id: 0.3
       bus info: pci@0000:03:00.3
       logical name: eno4
       version: 01
       serial: ac:1f:6b:61:19:3f
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=igb driverversion=5.4.0-k duplex=full firmware=1.63, 0x800009fa latency=0 link=yes multicast=yes port=twisted pair promiscuous=yes speed=1Gbit/s
       resources: irq:68 memory:c7100000-c711ffff ioport:6000(size=32) memory:c7180000-c7183fff memory:900c0000-900dffff memory:900e0000-900fffff
  *-network:1
       description: Ethernet interface
       product: I350 Gigabit Fiber Network Connection
       vendor: Intel Corporation
       physical id: 0.1
       bus info: pci@0000:82:00.1
       logical name: ens4f1
       version: 01
       serial: 68:91:d0:63:77:6f
       size: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress bus_master cap_list ethernet physical fibre autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=igb driverversion=5.4.0-k duplex=full firmware=1.52.0 latency=0 link=yes multicast=yes port=fibre speed=1Gbit/s
       resources: irq:89 memory:fbe00000-fbe1ffff memory:fbe40000-fbe43fff memory:fbe88000-fbea7fff memory:fbea8000-fbec7fff
```

now i found when i use eno4, it MUST be crash, but when i use `ens4f1`, it's not.

**Comment by Ivlyth** [comment]
Hi @cardigliano ,  i split the packet that cause the kernel panic .  

[one-fatal-packet.pcap.log](https://github.com/ntop/PF_RING/files/3770239/one-fatal-packet.pcap.log)

**Comment by cardigliano** [comment]
Can I see  ethtool -k <dev> on both interfaces?

**Comment by cardigliano** [comment]
@MythRen I pushed a patch that could fix this. Please update to latest code from github (or wait for the next packages) and let me know. Thank you.

**Comment by Ivlyth** [comment]
@cardigliano  
patch the [commit](https://github.com/ntop/PF_RING/commit/dc28ebc2f56ed61179769412aadb306f002826cb) manually to 6.4.0, but still cause kernel panic.  

trying 7.4.0, please wait for a moment

**Comment by Ivlyth** [comment]
@cardigliano 

PF_RING 7.4 still not work

**Comment by cardigliano** [comment]
Please let me see ethtool -k on both interfaces (I am not able to reproduce this, I need to check for differences in the configuration)

**Comment by Ivlyth** [comment]
@cardigliano 

latest dev branch not work too ... :(

**Comment by Ivlyth** [comment]
currently i use eno2:

```
[root@prs-sensor ~]# ethtool -k eno2
Features for eno2:
rx-checksumming: off
tx-checksumming: off
	tx-checksum-ipv4: off [fixed]
	tx-checksum-ip-generic: off
	tx-checksum-ipv6: off [fixed]
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: off
scatter-gather: off
	tx-scatter-gather: off
	tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: off
	tx-tcp-segmentation: off
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp6-segmentation: off
	tx-tcp-mangleid-segmentation: off
udp-fragmentation-offload: off [fixed]
generic-segmentation-offload: off
generic-receive-offload: off
large-receive-offload: off [fixed]
rx-vlan-offload: on
tx-vlan-offload: on
ntuple-filters: off
receive-hashing: on
highdma: on [fixed]
rx-vlan-filter: on [fixed]
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: on
tx-ipip-segmentation: on
tx-sit-segmentation: on
tx-udp_tnl-segmentation: on
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
busy-poll: off [fixed]
tx-gre-csum-segmentation: on
tx-udp_tnl-csum-segmentation: on
tx-gso-partial: on
tx-sctp-segmentation: off [fixed]
rx-gro-hw: off [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: on
rx-udp_tunnel-port-offload: off [fixed]
```

**Comment by cardigliano** [comment]
Please run "ethtool -K eno2 rxvlan off" and see if you are still able to reproduce the issue

**Comment by Ivlyth** [comment]
@cardigliano 

still cause kernel panic after i run `ethtool -K eno2 rxvlan off`

**Comment by Ivlyth** [comment]
Hi @cardigliano , can you reproduce the problem with the given packet ?

**Comment by cardigliano** [comment]
@MythRen I was unable to reproduce it so far, I am checking on different testbeds to see if we are able to reproduce it somewhere. I didn't find bugs with static code analysis. Any chance we can ssh to your system perhaps?

**Comment by Ivlyth** [comment]
@cardigliano do you mean you can reproduce it before the patch ?

**Comment by Ivlyth** [comment]
@cardigliano please send me an email to email4myth@gmail.com , then i will reply you with the ssh info 。

**Comment by Ivlyth** [comment]
@cardigliano ,  I just want to confirm whether you have sent the mail, because i have not received the mail from you. 
The problem is critical to me, help plz.

**Comment by cardigliano** [comment]
@MythRen I sent you an email right now.
Btw, I was not able to reproduce the issue even before.

**Comment by Ivlyth** [comment]
Hi @cardigliano , have you try it on my machine that I told you in the email ?

**Comment by cardigliano** [comment]
@MythRen I sent you an email 1h ago, please check that mail thread.

**Comment by Ivlyth** [comment]
@cardigliano , it's about how I18N (internationalization) works.   
you can contact me through tg or whatsapp in realtime, if you wish

**Comment by Ivlyth** [comment]
@cardigliano I’m online for the next four hours. 

Let me known if you need any help

**Comment by cardigliano** [comment]
Fixed with https://github.com/ntop/PF_RING/commit/3d151fb7d98256e4fe40885796eb382e34c3caee
Please confirm. Thank you.

**Comment by Ivlyth** [comment]
@cardigliano the problem solved, thank you very much
