### ISSUE TITLE
PF_RING call `pfring_open` with channel param in device_name gets an error

### ISSUE THREAD

**Issue by poetlife** [ntop/PF_RING#824]
### Problem description
When I called `pfring_open` in standard mode with channel param in device_name, it gets an error:
```bash
no such device
```
Here is my code:
```c
#include <stdio.h>
#include <pfring.h>

int main(int argc, char* argv[]){
    char *dev_name;
    if (argc == 2){
        dev_name = argv[1];
    }else{
        dev_name = "ens4f0";
    }
    printf("dev name is: %s\n", dev_name);
    pfring *pf;
    pf = pfring_open(dev_name, 1500, PF_RING_PROMISC);
    if (pf == NULL){
        printf("Error is: %s\n", strerror(errno));
        return -1;
    }else{
        printf("Have ring handle Error is: %s\n", strerror(errno));
    }
    pfring_close(pf);
    printf("exit the program\n");
    return 0;
}
```
I compiled this code successfully, and ran it with a channel Nic name:
```bash
./demo ens4f0@0
```
Then I got:
```bash
~ sudo ./demo ens4f0@0
dev name is: ens4f0@0
Have ring handle Error is: No such device
exit the program
```
And at the same time, I can run `pfcount -i ens4f0@0` successfully!
### Problem Impact
This problem will cause [gopacket](https://github.com/google/gopacket) cannot use pfring to capture the channel of the Nic. Besides, this error may mislead the user who uses it.

### System Info
Network Card: X710-T4L-t
Network Card Driver: i40e
OS: Ubuntu 20.04 LTS
Kernel: 5.13.0-52-generic
CPU: Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz
PF_Ring Version: latest

**Comment by poetlife** [comment]
Also I found this commit 70f63400101dfe4b9f493da051a8ba65f520cb0f may cause this issue.

**Comment by cardigliano** [comment]
@poetlife I pushed some fix for errno based on the commit you mentioned, please check it now

**Comment by poetlife** [comment]
It seems still get the  errno in `pfring_get_bound_device_ifindex(ring, &ring->device_id);` statement. And if we don't care about this error, shoud we set the errno to 0 when return the ring?

**Comment by cardigliano** [comment]
@poetlife I just pushed a fix for this as well in pfring_open

**Comment by poetlife** [comment]
Thx, I have already checked it, it works correctly now.
